export const collegeCourses = [
  "Bachelor of Early Childhood Education (BECED)",
  "Bachelor of Elementary Education (BEEd)",
  "Bachelor of Secondary Education (BSEd)",
  "Bachelor of Physical Education (BPEd)",
  "Bachelor of Special Needs Education (BSNEd)",
  "Bachelor of Technical-Vocational Teacher Education (BTVTEd)",
  "Bachelor of Science in Civil Engineering (BSCE)",
  "Bachelor of Science in Mechanical Engineering (BSME)",
  "Bachelor of Science in Electrical Engineering (BSEE)",
  "Bachelor of Science in Electronics Engineering (BSECE)",
  "Bachelor of Science in Computer Engineering (BSCpE)",
  "Bachelor of Science in Industrial Engineering (BSIE)",
  "Bachelor of Science in Chemical Engineering (BSCHE)",
  "Bachelor of Science in Architecture (BSArch)",
  "Bachelor of Science in Information Technology (BSIT)",
  "Bachelor of Science in Computer Science (BSCS)",
  "Bachelor of Science in Information Systems (BSIS)",
  "Bachelor of Library and Information Science (BLIS)",
  "Bachelor of Science in Accountancy (BSA)",
  "Bachelor of Science in Business Administration (BSBA)",
  "Bachelor of Science in Entrepreneurship (BSEntrep)",
  "Bachelor of Science in Hospitality Management (BSHM)",
  "Bachelor of Science in Tourism Management (BSTM)",
  "Bachelor of Science in Nursing (BSN)",
  "Bachelor of Science in Medical Technology (BSMT)",
  "Bachelor of Science in Pharmacy",
  "Bachelor of Science in Physical Therapy (BSPT)",
  "Doctor of Dental Medicine (DMD)",
  "Bachelor of Science in Agriculture (BSA)",
  "Bachelor of Science in Forestry (BSF)",
  "Bachelor of Science in Fisheries (BSFi)",
  "Bachelor of Arts in English Language Studies",
  "Bachelor of Arts in Communication",
  "Bachelor of Arts in Political Science",
  "Bachelor of Arts in Psychology",
  "Bachelor of Fine Arts (BFA)",
  "Bachelor of Science in Biology",
  "Bachelor of Science in Chemistry",
  "Bachelor of Science in Physics",
  "Bachelor of Science in Mathematics",
  "Bachelor of Science in Statistics",
  "Bachelor of Science in Criminology (BSCrim)",
  "Bachelor of Theology (BTh)"
];

export const graduateCourses = [
  "Master of Arts in Education (MAEd)",
  "Master in Education (MEd)",
  "Master of Arts in Teaching (MAT)",
  "Master in Educational Management",
  "Master in Special Education",
  "Master in Physical Education",
  "Master in Early Childhood Education",
  "Master in Business Administration (MBA)",
  "Executive MBA",
  "Master in Public Administration (MPA)",
  "Master in Management",
  "Master in Entrepreneurship",
  "Master in Human Resource Management",
  "Master in Information Technology (MIT)",
  "Master of Science in Information Technology (MSIT)",
  "Master of Science in Computer Science (MSCS)",
  "Master in Data Science",
  "Master in Cybersecurity",
  "Master of Science in Civil Engineering",
  "Master of Science in Electrical Engineering",
  "Master of Science in Mechanical Engineering",
  "Master of Engineering Programs",
  "Master in Industrial Engineering",
  "Master of Science in Nursing (MSN)",
  "Master in Public Health (MPH)",
  "Master of Science in Medical Technology",
  "Master of Science in Pharmacy",
  "Master in Hospital Administration",
  "Doctor of Education (EdD)",
  "Doctor of Philosophy in Education (PhD Education)",
  "Doctor in Business Administration (DBA)",
  "Doctor in Public Administration (DPA)",
  "PhD in Business Administration",
  "PhD in Biology",
  "PhD in Chemistry",
  "PhD in Physics",
  "PhD in Mathematics",
  "PhD in Information Technology",
  "PhD in Engineering",
  "Juris Doctor (JD)",
  "Doctor of Medicine (MD)",
  "Doctor of Dental Medicine (DMD)",
  "Doctor of Veterinary Medicine (DVM)"
];

export const yearLevels = [
  { group: "Nursery / Kindergarten", options: ["NURSERY", "KINDERGARTEN"] },
  { group: "Elementary", options: ["GRADE 1", "GRADE 2", "GRADE 3", "GRADE 4", "GRADE 5", "GRADE 6"] },
  { group: "Junior High School", options: ["GRADE 7", "GRADE 8", "GRADE 9", "GRADE 10"] },
  { group: "Senior High School", options: ["GRADE 11", "GRADE 12"] },
  { group: "College", options: ["1ST YEAR COLLEGE", "2ND YEAR COLLEGE", "3RD YEAR COLLEGE", "4TH YEAR COLLEGE", "5TH YEAR COLLEGE"] },
  { group: "Graduate School", options: ["1ST YEAR GRADUATE SCHOOL", "2ND YEAR GRADUATE SCHOOL"] },
  { group: "Professional / Career", options: ["PROFESSIONAL", "WORKING"] },
  { group: "Alternative / Non-Formal Education", options: ["ALS", "OUT OF SCHOOL"] }
];
